# Generated by Django 3.1.7 on 2021-03-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aft', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
