# Generated by Django 3.1.7 on 2021-03-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aft', '0008_auto_20210331_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
