# Generated by Django 3.2.3 on 2021-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aft', '0009_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_pic',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
