# Generated by Django 3.2.3 on 2021-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blog_category'),
        ('aft', '0012_profile_following_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following_category',
            field=models.ManyToManyField(blank=True, related_name='following_category', to='blog.Category'),
        ),
    ]
