# Generated by Django 3.1.7 on 2021-03-30 09:18

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='full_text',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
