# Generated by Django 3.1.7 on 2021-04-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.CharField(default='def', max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
