# Generated by Django 3.1.7 on 2021-04-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='No',
            field=models.CharField(default='default', max_length=100, verbose_name='No'),
            preserve_default=False,
        ),
    ]
