# Generated by Django 3.2.3 on 2021-06-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210604_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='No',
        ),
    ]
