# Generated by Django 3.2.3 on 2021-06-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aft', '0011_profile_following'),
        ('blog', '0010_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aft.profile'),
        ),
    ]
