# Generated by Django 3.2.3 on 2021-06-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.OneToOneField(default='other', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.category'),
        ),
    ]
